#!/usr/bin/env python3
"""Regenerate cammello/assets/camera_map.json from Wikidata (0.15.0).

Cameras carry their EXIF model string on Wikidata as P2009 "Exif model"
(plus P2010 "Exif make"), so the camera mapping is a QUERY, not a guess:

    SELECT ?item ?model ?make WHERE {
      ?item wdt:P2009 ?model .
      OPTIONAL { ?item wdt:P2010 ?make }
    }

Only UNAMBIGUOUS mappings are kept: a model string that belongs to
several items is dropped, unless make+model together are unique (then the
key is "make\\tmodel"). Lenses have NO Exif-string property on Wikidata -
the "lenses" section is curated by hand and is preserved across runs.

Run this whenever the snapshot feels stale:  python3 make_camera_map.py
"""
import collections
import json
import os
import sys

import requests

ENDPOINT = 'https://query.wikidata.org/sparql'
QUERY = ('SELECT ?item ?model ?make WHERE { ?item wdt:P2009 ?model . '
         'OPTIONAL { ?item wdt:P2010 ?make } }')
TARGET = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                      'cammello', 'assets', 'camera_map.json')
USER_AGENT = 'Cammello camera-map updater (https://github.com/krichel89/Cammello)'


def main():
    print('Asking Wikidata…')
    r = requests.get(ENDPOINT, params={'query': QUERY, 'format': 'json'},
                     headers={'User-Agent': USER_AGENT}, timeout=120)
    r.raise_for_status()
    rows = r.json()['results']['bindings']
    print(f'{len(rows)} statements.')

    by_model = collections.defaultdict(set)
    by_make_model = collections.defaultdict(set)
    for b in rows:
        qid = b['item']['value'].rsplit('/', 1)[-1]
        model = b.get('model', {}).get('value', '').strip()
        make = b.get('make', {}).get('value', '').strip()
        if not model:
            continue
        by_model[model].add(qid)
        if make:
            by_make_model[(make, model)].add(qid)

    cameras = {m: next(iter(q)) for m, q in by_model.items() if len(q) == 1}
    extra = 0
    for (make, model), qids in by_make_model.items():
        if len(qids) == 1 and model not in cameras:
            cameras[make + '\t' + model] = next(iter(qids))
            extra += 1
    print(f'{len(cameras) - extra} unambiguous by model, '
          f'{extra} more by make+model.')

    lenses = {'_comment': 'EXIF LensModel string -> QID (P11385). Curated '
              'by hand - Wikidata has no Exif-string property for lenses.'}
    if os.path.exists(TARGET):
        try:
            lenses = json.load(open(TARGET, encoding='utf-8')).get(
                'lenses', lenses)
        except (ValueError, OSError):
            print('Warning: existing file unreadable, lens list reset.')

    from datetime import date
    out = {
        '_comment': 'EXIF model string -> Wikidata QID (P4082 source). '
                    'Keys are the P2009 value, or "make\\tmodel" where the '
                    'model alone is ambiguous. Generated by '
                    'make_camera_map.py from Wikidata (P2009/P2010); this '
                    f'snapshot: {date.today().isoformat()}. Only '
                    'UNAMBIGUOUS mappings are included.',
        'cameras': dict(sorted(cameras.items())),
        'lenses': lenses,
    }
    json.dump(out, open(TARGET, 'w', encoding='utf-8'),
              ensure_ascii=False, indent=1)
    print(f'Written: {TARGET} ({os.path.getsize(TARGET)} bytes, '
          f'{len(cameras)} cameras, {len(lenses) - 1} lenses kept).')
    return 0


if __name__ == '__main__':
    sys.exit(main())
